name: Build and Deploy to Docker Hub

on:
  push:
    paths:
      - "server/**"
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: tamalcdip/rankdevs-docker-img:latest

      - name: Verify Pushed Image
        run: docker pull tamalcdip/rankdevs-docker-img:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull tamalcdip/rankdevs-docker-img:latest
            sudo docker stop rankdevs-docker-img || true
            sudo docker rm rankdevs-docker-img || true
            sudo docker run -d --name rankdevs-docker-img -p 3001:3001 tamalcdip/rankdevs-docker-img:latest
